base_url = "https://xtrayambak.xyz"
compile_sass = true
build_search_index = true
theme = "zolanight"
taxonomies = [{ name = "tags" }]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here

[extra.zolanight]
theme = "tokyonight"
home_list_latest_blog_posts = true
google_analytics_id = ""
ko_fi_url = ""
